spring.application.name=omapp

spring.datasource.url=jdbc:postgresql://localhost:5432/omadb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.whitelabel.enabled=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

SUPABASE_URL=https://zxymipknskrughkxancc.supabase.co
SUPABASE_KEY=sb_publishable_hKhHiEt5xjBbk9WLcNJZ1Q__sYI4oQK
SUPABASE_BUCKET=media